#!/bin/bash

# ============================================
# PVP数据看板系统 - 原生环境一键部署脚本 (CentOS)
# ============================================

set -e  # 遇到错误立即退出

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# 日志函数
log_info() {
    echo -e "${BLUE}[INFO]${NC} $1"
}

log_success() {
    echo -e "${GREEN}[SUCCESS]${NC} $1"
}

log_warning() {
    echo -e "${YELLOW}[WARNING]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

# 检查是否为root用户
check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "此脚本需要root权限运行"
        log_info "请使用: sudo $0"
        exit 1
    fi
}

# 检查系统版本
check_centos() {
    if [[ -f /etc/redhat-release ]]; then
        local version=$(cat /etc/redhat-release)
        log_info "检测到系统: $version"
    else
        log_warning "未检测到CentOS/RHEL系统，继续执行..."
    fi
}

# 检查并配置DNS
check_and_config_dns() {
    log_info "检查DNS配置..."
    
    # 测试DNS解析
    if ! nslookup mirrors.aliyun.com > /dev/null 2>&1 && ! ping -c 1 -W 2 mirrors.aliyun.com > /dev/null 2>&1; then
        log_warning "DNS解析失败，尝试配置DNS服务器..."
        
        # 检查resolv.conf
        if ! grep -q "nameserver 8.8.8.8" /etc/resolv.conf 2>/dev/null; then
            log_info "配置DNS服务器..."
            # 备份原配置
            cp /etc/resolv.conf /etc/resolv.conf.bak.$(date +%Y%m%d_%H%M%S) 2>/dev/null || true
            
            # 添加DNS服务器
            {
                echo "# Generated by deploy script"
                echo "nameserver 8.8.8.8"
                echo "nameserver 114.114.114.114"
                echo "nameserver 223.5.5.5"
                if [[ -f /etc/resolv.conf ]]; then
                    grep -v "^nameserver" /etc/resolv.conf | grep -v "^# Generated" || true
                fi
            } > /tmp/resolv.conf.new
            
            mv /tmp/resolv.conf.new /etc/resolv.conf
            log_success "DNS配置已更新"
        fi
        
        # 再次测试
        sleep 2
        if ! nslookup mirrors.aliyun.com > /dev/null 2>&1 && ! ping -c 1 -W 2 mirrors.aliyun.com > /dev/null 2>&1; then
            log_error "DNS仍然无法解析，请检查网络连接"
            read -p "是否继续部署? (y/n): " -n 1 -r
            echo
            if [[ ! $REPLY =~ ^[Yy]$ ]]; then
                exit 1
            fi
        else
            log_success "DNS解析正常"
        fi
    else
        log_success "DNS解析正常"
    fi
}

# 检查并安装Python 3
install_python3() {
    log_info "检查Python 3..."
    
    if command -v python3 &> /dev/null; then
        local version=$(python3 --version 2>&1)
        log_success "Python 3已安装: $version"
        
        # 检查版本是否 >= 3.7
        local major=$(python3 -c "import sys; print(sys.version_info.major)" 2>/dev/null)
        local minor=$(python3 -c "import sys; print(sys.version_info.minor)" 2>/dev/null)
        
        if [[ "$major" -lt 3 ]] || [[ "$major" -eq 3 && "$minor" -lt 7 ]]; then
            log_warning "Python版本过低 ($major.$minor)，需要 >= 3.7"
            log_info "尝试安装Python 3.7+..."
            install_python3_from_source
        fi
    else
        log_info "Python 3未安装，开始安装..."
        install_python3_from_source
    fi
    
    # 检查pip
    if ! command -v pip3 &> /dev/null; then
        log_info "安装pip..."
        yum install -y python3-pip || {
            log_warning "yum安装pip失败，尝试使用get-pip.py..."
            curl -sSL https://bootstrap.pypa.io/get-pip.py | python3
        }
    fi
    
    log_success "Python 3环境就绪"
}

# 从源码安装Python 3（如果需要）
install_python3_from_source() {
    log_info "从EPEL仓库安装Python 3..."
    
    # 安装EPEL仓库
    if ! rpm -qa | grep -q epel-release; then
        log_info "安装EPEL仓库..."
        yum install -y epel-release || {
            log_warning "EPEL安装失败，尝试使用阿里云镜像..."
            yum install -y https://mirrors.aliyun.com/epel/epel-release-latest-7.noarch.rpm || true
        }
    fi
    
    # 安装Python 3
    yum install -y python3 python3-pip python3-devel || {
        log_error "Python 3安装失败"
        exit 1
    }
}

# 检查并安装PostgreSQL
install_postgresql() {
    log_info "检查PostgreSQL..."
    
    if command -v psql &> /dev/null; then
        local version=$(psql --version 2>&1 | head -1)
        log_success "PostgreSQL已安装: $version"
        
        # 检查PostgreSQL服务是否运行
        if systemctl is-active --quiet postgresql || systemctl is-active --quiet postgresql-server; then
            log_success "PostgreSQL服务正在运行"
        else
            log_warning "PostgreSQL服务未运行，尝试启动..."
            start_postgresql_service
        fi
    else
        log_info "PostgreSQL未安装，开始安装..."
        
        # 安装PostgreSQL仓库
        if [[ ! -f /etc/yum.repos.d/pgdg-redhat-all.repo ]]; then
            log_info "添加PostgreSQL官方仓库..."
            yum install -y https://download.postgresql.org/pub/repos/yum/reporpms/EL-7-x86_64/pgdg-redhat-repo-latest.noarch.rpm 2>&1 | grep -v "already installed" || {
                log_warning "官方仓库添加失败，使用系统仓库..."
            }
        fi
        
        # 安装PostgreSQL 15（如果可用）或系统默认版本
        if yum list available postgresql15-server &> /dev/null; then
            log_info "安装PostgreSQL 15..."
            yum install -y postgresql15-server postgresql15
            POSTGRES_VERSION="15"
        elif yum list available postgresql12-server &> /dev/null; then
            log_info "安装PostgreSQL 12..."
            yum install -y postgresql12-server postgresql12
            POSTGRES_VERSION="12"
        else
            log_info "安装系统默认PostgreSQL版本..."
            yum install -y postgresql-server postgresql
            POSTGRES_VERSION=""
        fi
        
        # 初始化数据库
        log_info "初始化PostgreSQL数据库..."
        if [[ -n "$POSTGRES_VERSION" ]]; then
            /usr/pgsql-${POSTGRES_VERSION}/bin/postgresql-${POSTGRES_VERSION}-setup initdb || {
                log_warning "初始化失败，可能已经初始化过"
            }
        else
            postgresql-setup initdb || {
                log_warning "初始化失败，可能已经初始化过"
            }
        fi
        
        # 启动服务
        start_postgresql_service
        
        log_success "PostgreSQL安装完成"
    fi
}

# 启动PostgreSQL服务
start_postgresql_service() {
    local service_name=""
    
    # 检测服务名称
    if systemctl list-unit-files | grep -q "postgresql-15"; then
        service_name="postgresql-15"
    elif systemctl list-unit-files | grep -q "postgresql-12"; then
        service_name="postgresql-12"
    elif systemctl list-unit-files | grep -q "postgresql-server"; then
        service_name="postgresql-server"
    else
        service_name="postgresql"
    fi
    
    log_info "启动PostgreSQL服务: $service_name"
    systemctl enable $service_name
    systemctl start $service_name
    
    # 等待服务启动
    local retries=0
    while [[ $retries -lt 10 ]]; do
        if systemctl is-active --quiet $service_name; then
            log_success "PostgreSQL服务已启动"
            sleep 2  # 等待服务完全就绪
            return 0
        fi
        retries=$((retries + 1))
        sleep 1
    done
    
    log_error "PostgreSQL服务启动失败"
    exit 1
}

# 配置PostgreSQL数据库
configure_postgresql() {
    log_info "配置PostgreSQL数据库..."
    
    # 检测PostgreSQL版本和路径
    local psql_path=""
    local pg_version=""
    
    if command -v psql &> /dev/null; then
        psql_path=$(which psql)
        pg_version=$(psql --version | grep -oE '[0-9]+\.[0-9]+' | head -1 | cut -d. -f1)
    fi
    
    # 检测数据目录
    local pg_data_dir=""
    if [[ -d /var/lib/pgsql/${pg_version}/data ]]; then
        pg_data_dir="/var/lib/pgsql/${pg_version}/data"
    elif [[ -d /var/lib/pgsql/data ]]; then
        pg_data_dir="/var/lib/pgsql/data"
    else
        log_warning "无法找到PostgreSQL数据目录，使用默认配置"
    fi
    
    # 配置PostgreSQL允许本地连接（如果需要）
    if [[ -n "$pg_data_dir" ]] && [[ -f "${pg_data_dir}/pg_hba.conf" ]]; then
        log_info "配置PostgreSQL认证方式..."
        # 确保本地连接使用md5或trust
        if ! grep -q "^local.*all.*all.*md5\|^local.*all.*all.*trust" "${pg_data_dir}/pg_hba.conf"; then
            # 备份配置文件
            cp "${pg_data_dir}/pg_hba.conf" "${pg_data_dir}/pg_hba.conf.bak.$(date +%Y%m%d_%H%M%S)"
            
            # 添加本地连接配置（如果不存在）
            if ! grep -q "^local.*all.*all" "${pg_data_dir}/pg_hba.conf"; then
                sed -i '/^# "local" is for Unix domain socket connections only/a local   all             all                                     md5' "${pg_data_dir}/pg_hba.conf"
            fi
        fi
        
        # 重启服务使配置生效
        if systemctl is-active --quiet postgresql-${pg_version} || systemctl is-active --quiet postgresql-server; then
            log_info "重启PostgreSQL服务使配置生效..."
            systemctl restart postgresql-${pg_version} 2>/dev/null || systemctl restart postgresql-server 2>/dev/null || true
            sleep 2
        fi
    fi
    
    # 创建数据库和用户
    log_info "创建数据库和用户..."
    
    # 检查用户是否存在
    if sudo -u postgres psql -tAc "SELECT 1 FROM pg_roles WHERE rolname='app';" 2>/dev/null | grep -q 1; then
        log_info "数据库用户 'app' 已存在"
    else
        log_info "创建数据库用户: app"
        sudo -u postgres psql -c "CREATE USER app WITH PASSWORD 'app';" 2>/dev/null || {
            log_warning "创建用户失败，可能已存在或权限不足"
        }
    fi
    
    # 检查数据库是否存在
    if sudo -u postgres psql -tAc "SELECT 1 FROM pg_database WHERE datname='pvp';" 2>/dev/null | grep -q 1; then
        log_info "数据库 'pvp' 已存在"
    else
        log_info "创建数据库: pvp"
        sudo -u postgres psql -c "CREATE DATABASE pvp OWNER app;" 2>/dev/null || {
            log_warning "创建数据库失败，可能已存在或权限不足"
        }
    fi
    
    # 授予权限
    log_info "授予数据库权限..."
    sudo -u postgres psql -d pvp -c "GRANT ALL PRIVILEGES ON DATABASE pvp TO app;" 2>/dev/null || true
    sudo -u postgres psql -d pvp -c "GRANT ALL ON SCHEMA public TO app;" 2>/dev/null || true
    
    log_success "PostgreSQL配置完成"
}

# 创建Python虚拟环境
setup_python_venv() {
    log_info "设置Python虚拟环境..."
    
    local project_dir=$(pwd)
    
    if [[ -d "${project_dir}/.venv" ]]; then
        log_info "虚拟环境已存在，跳过创建"
    else
        log_info "创建虚拟环境..."
        python3 -m venv .venv || {
            log_error "虚拟环境创建失败"
            exit 1
        }
    fi
    
    log_info "激活虚拟环境并安装依赖..."
    source .venv/bin/activate
    
    # 升级pip
    pip install --upgrade pip -i https://pypi.tuna.tsinghua.edu.cn/simple || {
        log_warning "使用清华镜像源失败，尝试官方源..."
        pip install --upgrade pip
    }
    
    # 安装依赖
    if [[ -f requirements.txt ]]; then
        log_info "安装Python依赖包..."
        pip install -r requirements.txt -i https://pypi.tuna.tsinghua.edu.cn/simple || {
            log_warning "使用清华镜像源失败，尝试官方源..."
            pip install -r requirements.txt
        }
        log_success "Python依赖安装完成"
    else
        log_error "未找到requirements.txt文件"
        exit 1
    fi
}

# 创建必要的目录
create_directories() {
    log_info "创建必要的目录..."
    mkdir -p data_logs
    log_success "目录创建完成"
}

# 检查端口占用
check_ports() {
    local ports=(8090 5432)
    local conflicts=()
    
    for port in "${ports[@]}"; do
        if netstat -tuln 2>/dev/null | grep -q ":$port "; then
            conflicts+=($port)
        fi
    done
    
    if [[ ${#conflicts[@]} -gt 0 ]]; then
        log_warning "以下端口已被占用: ${conflicts[*]}"
        read -p "是否继续部署? (y/n): " -n 1 -r
        echo
        if [[ ! $REPLY =~ ^[Yy]$ ]]; then
            exit 1
        fi
    fi
}

# 检查必要的文件
check_files() {
    local required_files=("requirements.txt" "backend/app/main.py")
    local missing_files=()
    
    for file in "${required_files[@]}"; do
        if [[ ! -f "$file" ]]; then
            missing_files+=($file)
        fi
    done
    
    if [[ ${#missing_files[@]} -gt 0 ]]; then
        log_error "缺少必要文件: ${missing_files[*]}"
        log_error "请确保在项目根目录运行此脚本"
        exit 1
    fi
    
    log_success "所有必要文件检查通过"
}

# 测试数据库连接
test_database_connection() {
    log_info "测试数据库连接..."
    
    source .venv/bin/activate
    
    python3 << 'PYEOF'
import sys
import os
os.environ.setdefault('POSTGRES_HOST', 'localhost')
os.environ.setdefault('POSTGRES_PORT', '5432')
os.environ.setdefault('POSTGRES_USER', 'app')
os.environ.setdefault('POSTGRES_PASSWORD', 'app')
os.environ.setdefault('POSTGRES_DB', 'pvp')

try:
    from backend.app.database import engine
    with engine.connect() as conn:
        print("✓ 数据库连接成功")
        sys.exit(0)
except Exception as e:
    print(f"✗ 数据库连接失败: {e}")
    sys.exit(1)
PYEOF

    if [[ $? -eq 0 ]]; then
        log_success "数据库连接测试通过"
    else
        log_error "数据库连接测试失败"
        exit 1
    fi
}

# 创建systemd服务文件（可选）
create_systemd_service() {
    log_info "创建systemd服务文件..."
    
    local service_file="/etc/systemd/system/pvp-data.service"
    local project_dir=$(pwd)
    local python_path="${project_dir}/.venv/bin/python"
    local uvicorn_path="${project_dir}/.venv/bin/uvicorn"
    
    cat > "$service_file" << EOF
[Unit]
Description=PVP Data Dashboard API Service
After=network.target postgresql.service

[Service]
Type=simple
User=root
WorkingDirectory=${project_dir}
Environment="PATH=${project_dir}/.venv/bin"
Environment="POSTGRES_HOST=localhost"
Environment="POSTGRES_PORT=5432"
Environment="POSTGRES_USER=app"
Environment="POSTGRES_PASSWORD=app"
Environment="POSTGRES_DB=pvp"
Environment="IMPORT_DIR=${project_dir}/data_logs"
Environment="IMPORT_INTERVAL_SEC=300"
ExecStart=${uvicorn_path} backend.app.main:app --host 0.0.0.0 --port 8090
Restart=always
RestartSec=10

[Install]
WantedBy=multi-user.target
EOF

    log_success "systemd服务文件已创建: $service_file"
    log_info "可以使用以下命令管理服务:"
    log_info "  启动服务: systemctl start pvp-data"
    log_info "  停止服务: systemctl stop pvp-data"
    log_info "  查看状态: systemctl status pvp-data"
    log_info "  开机自启: systemctl enable pvp-data"
}

# 显示部署信息
show_deployment_info() {
    echo ""
    log_info "==================== 部署完成 ===================="
    echo ""
    
    local host_ip=$(hostname -I | awk '{print $1}')
    
    log_success "应用访问地址: http://${host_ip}:8090"
    log_success "本地访问地址: http://localhost:8090"
    log_success "健康检查: http://localhost:8090/api/health"
    log_success "数据库健康检查: http://localhost:8090/api/health/db"
    echo ""
    
    log_info "==================== 数据库信息 ===================="
    log_info "主机: localhost"
    log_info "端口: 5432"
    log_info "用户: app"
    log_info "密码: app"
    log_info "数据库: pvp"
    echo ""
    
    log_info "==================== 常用命令 ===================="
    echo "启动服务:"
    echo "  source .venv/bin/activate"
    echo "  uvicorn backend.app.main:app --host 0.0.0.0 --port 8090"
    echo ""
    echo "或使用systemd服务:"
    echo "  systemctl start pvp-data"
    echo ""
    echo "查看日志:"
    echo "  journalctl -u pvp-data -f"
    echo ""
    echo "导入数据:"
    echo "  source .venv/bin/activate"
    echo "  python -m backend.app.ingestion --logs_dir ./data_logs"
    echo ""
    echo "================================================"
}

# 主函数
main() {
    echo ""
    log_info "=========================================="
    log_info "  PVP数据看板系统 - 原生环境部署脚本"
    log_info "=========================================="
    echo ""
    
    # 执行检查
    check_root
    check_centos
    check_files
    check_ports
    create_directories
    
    # 检查并配置DNS
    check_and_config_dns
    
    # 安装依赖
    install_python3
    install_postgresql
    configure_postgresql
    
    # 设置Python环境
    setup_python_venv
    
    # 测试数据库连接
    test_database_connection
    
    # 创建systemd服务（可选）
    read -p "是否创建systemd服务? (y/n): " -n 1 -r
    echo
    if [[ $REPLY =~ ^[Yy]$ ]]; then
        create_systemd_service
        systemctl daemon-reload
        log_info "可以使用 'systemctl start pvp-data' 启动服务"
    fi
    
    # 显示部署信息
    show_deployment_info
    
    log_success "部署完成！"
}

# 执行主函数
main "$@"

